### ISSUE TITLE
Dependencies and import error

### ISSUE THREAD

**Issue by joolof** [bpairet/mayo_hci#1]
Hi, just saw the paper on astro-ph and the pipeline looks extremely interesting! Thanks a lot for making it available.
I cloned the repository and tried to run the example but I ran into some problems. 
The first one was regarding the import of simplex_projection.py. I found [this repository](https://gist.github.com/daien/1272551) and added it to the local directory but I wanted to make sure this was the correct module.
Second, I am running into a `ModuleNotFoundError: No module named 'disk_greedy_iter_rank'` at line 20 in mayonnaise.py, and this one I do not know how to solve it.
Thanks

**Comment by bpairet** [comment]
Hello ! Thanks for the interest in mayo_hci. I am very sorry this is a very early release and for some reasons I didn't have that import error locally. I just pushed a few modifications that should make it work now.
For the moment, I haven't had the time to list the requirements. In addition to the simplex_projection.py file, there is pyshearlab : https://github.com/stefanloock/pyshearlab
For the other requirements that I can think of, you should have no problem finding them, a list from the top of my head includes : vip_hci, torch, hciplot (for the example at least), sklearn, and of course numpy and scipy.
I hope this helps and again, sorry for the early release (there is a lack of comments as well). If you have any other question, don't hesitate to drop me an email.
Thanks

**Comment by joolof** [comment]
Thanks a lot for the quick reply and solving the issue. Seems to be working perfectly fine right now!
Cheers
